<h1>Cadastro de Produtos</h1>

<?php
	echo $this->form()->openTag($form);
?>

<div class="form-group">
<label for="nome">Nome:</label>
<?php 
	echo $this->formInput($form->get('nome'));	
?>
</div>

<div class="form-group">
<label for="preco">Preço:</label>
<?php 
	echo $this->formInput($form->get('preco'));	
?>
</div>

<div class="form-group">
<label for="descricao">Descrição:</label>
<?php 
	echo $this->formTextarea($form->get('descricao'));	
?>
</div>

<div class="form-group">
    <button class="btn btn-primary">Cadastrar produto</button>
</div>
<?php  
	echo $this->form()->closeTag();
?>

