<h1>Cadastro de Produtos</h1>

<form action="" method="post">

	<div class="form-group">
		<label for="nome">Nome</label>
		<input type="text" class="form-control" name="nome" id="nome" alt="Digite o nome do produto" placeholder="Digite o nome do produto">
    </div>

	<div class="form-group">
		<label for="preco">Preço</label>
		<input type="text" class="form-control" name="preco" id="preco" alt="Digite o preço do produto" placeholder="Digite o preço do produto">
	</div>
	
	<div class="form-group">
		<label for="descricao">Descrição</label>
		<textarea class="form-control" name="descricao" id="descricao" alt="Digite a descricão do produto" placeholder="Digite a descricão do produto"></textarea>
	</div>

	<div class="form-group">
		<button type="submit" class="btn btn-primary">Cadastrar</button>
	</div>

</form>