<h1>Entre em contato conosco !</h1>

<form method="post" action="<?= $this->url('application', ['action' => 'contato']); ?>">
	<div class="form-group">
		<label>Nome</label>
		<input type="text" name="nome" class="form-control" required="true">
	</div>
	<div class="form-group">
		<label>Email</label>
		<input type="email" name="email" class="form-control" required="true">
	</div>
	<div class="form-group">
		<label>Mensagem</label>
		<textarea name="mensagem" class="form-control" required="true"></textarea>
	</div>
	<div class="form-group">
		<button type="submit" class="btn btn-primary">Eviar email</button>
	</div>
</form>