<h1>Editar Produtos</h1>

<form method="post" action="<?= $this->url('application', ['action' => 'editar']); ?>">
	<input type="hidden" name="id" value="<?= $produto->getId(); ?>">
	<div class="form-group">
		<label for="nome">Nome</label>
		<input type="text" class="form-control" name="nome" id="nome" alt="Digite o nome do produto"
		  value="<?= $produto->getNome(); ?>">
    </div>

	<div class="form-group">
		<label for="preco">Preço</label>
		<input type="text" class="form-control" name="preco" id="preco" alt="Digite o preço do produto"  value="<?= $produto->getPreco(); ?>">
	</div>
	
	<div class="form-group">
		<label for="descricao">Descrição</label>
		<textarea class="form-control" name="descricao" id="descricao" alt="Digite a descricão do 
		  produto"><?= $produto->getDescricao(); ?></textarea>
	</div>

	<div class="form-group">
		<button type="submit" class="btn btn-primary">Editar</button>
	</div>

</form>