<h1>Listagem de produtos</h1>

<table class="table table-striped table-hover">
	<thead>
		<tr>
			<th>Nome</th>
			<th>Preço</th>
			<th>Descricão</th>
			<th>Categoria</th>
			<th>Ações</th>
		</tr>
	</thead>
	<tbody>
		<?php
			foreach($produtos as $produto): ?>
				<tr>
					<td><?= $produto->getNome(); ?></td>
					<td><?= $produto->getPreco(); ?></td>
					<td><?= $produto->getDescricao(); ?></td>
					<td><?= $produto->getCategoria()->getNome(); ?></td>
					<td><a href="<?= $this->url('application', ['action' => 'remover', 'id' => $produto->getId()]);?>" class="btn btn-danger btn-sm">Remover</a>
					    <a href="<?= $this->url('application', ['action' => 'editar', 'id' => $produto->getId()]);?>" class="btn btn-info btn-sm">Editar</a>
					</td>

				</tr>
			<?php endforeach;	
		?>
	</tbody>
</table>

<?php
	echo $this->PaginationHelper($produtos, $qtdPorPagina,'/Produtos');
?>