<h1>Listagem de produtos</h1>

<table class="table table-striped table-hover">
	<thead>
		<tr>
			<th>Nome</th>
			<th>Preço</th>
			<th>Descricão</th>
			<th>Ações</th>
		</tr>
	</thead>
	<tbody>
		<?php
			foreach($produtos as $produto): ?>
				<tr>
					<td><?= $produto->getNome(); ?></td>
					<td><?= $produto->getPreco(); ?></td>
					<td><?= $produto->getDescricao(); ?></td>
					<td><a href="<?= $this->url('application', ['action' => 'remover', 'id' => $produto->getId()]);?>" class="btn btn-danger btn-sm">Remover</a></td>
				</tr>
			<?php endforeach;	
		?>
	</tbody>
</table>
