<h1>Identifique-se para acessar o sistema</h1>

<?php $url = $this->url('application', ['controller' => 'Usuario', 'action' =>'login']); ?>

<form action="<?= $url ?>" method="post">
	<div class="form-group">
		<label for="email">Email:</label>
		<input class="form-control" type="email" name="email" id="email" placeholder="Digite seu E-mail" alt="Digite seu E-mail" required="true">
	</div>	
	<div class="form-group">
		<label for="password">Senha</label>
		<input class="form-control" type="password" name="password" id="password" placeholder="Digite sua senha" alt="Digite sua senha" required="true">
	</div>
	<div class="form-group">
		<button class="btn btn-primary" type="submit" alt="Clique aqui para acessar o sistema" >Acessar o sistema</button>
	</div>
</form>