<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Sistema de Estoque</title>
    <?php echo $this->headLink()
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

    <?php echo $this->headScript()
                        ->prependFile($this->basePath('js/bootstrap.min.js'))
                        ->prependFile($this->basePath('js/jquery.min.js'))
                        ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                        ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
                    ; ?>
</head>
<body>
    <header>
        <nav class="navbar navbar-default">
            <div class="navbar-head">
                <a href="#" class="navbar-brand">Kunstee</a>
            </div>
            <ul class="nav navbar-nav">
                <li><a href="<?= $this->url('application', ['action' =>'Index']); ?>">Listagem dos produtos</a></li>
                <li><a href="<?= $this->url('application', ['action' =>'cadastrar']); ?>">Cadastro de produtos</a></li>
            </ul>
        </nav>
    </header>

    <main class="conteudo">
        <?php 
            $this->flashHelper(); 
            echo $this->content;
        ?>
    </main>

    <footer class="rodape">Todos os direitos reservados</footer>
</body>
</html>